name: 👓 Review Auto
on:
  push:
    branches:
      - "feat/**"
      - "fix/**"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  socialgouv:
    name: "🇫🇷 SocialGouv"
    uses: socialgouv/workflows/.github/workflows/use-ks-gh-review-auto.yaml@feat/trivy-scan
    secrets: inherit

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker pull harbor.fabrique.social.gouv.fr/sandbox/sandbox-ks-gh/app'
          severity: 'CRITICAL'  
          exit-code: '1'
          timeout: "20m"
          format: 'table'
          trivy-config: "trivy.yaml"