name: 👓 Review Auto
on:
  push:
    branches:
      - "feat/**"
      - "fix/**"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  socialgouv:
    uses: socialgouv/workflows/.github/workflows/use-ks-gh-review-auto.yaml@feat/trivy-scan
    secrets: inherit
