name: Test tty
on:
  push:
    branches:
      - "**"
      - "!master"
      - "!main"
      - "!feat/**"
      - "!fix/**"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  kontinuous:
    runs-on: ubuntu-latest
    steps:
      - run: node -e "console.log(process.stdout.isTTY)"
